apiVersion: v1
kind: Service

metadata:
  name: student-management-service

spec:
  selector:
    app: student-management

  type: NodePort

  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007