apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-management-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: student-management

  template:
    metadata:
      labels:
        app: student-management

    spec:
      containers:
        - name: student-management-container
          image: student-management-system:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 3000